# Generated by Django 5.1.5 on 2025-03-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipe_created_on_alter_recipe_updated_on'),
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraccounts.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
